include subdirectories when auto-title

diff --git a/common/set_title b/common/set_title
--- a/common/set_title
+++ b/common/set_title
@@ -17,18 +17,27 @@ COL_RED="\033[91m"
 COL_DEFAULT="\033[39m"
 
 replace_title() {
-  if [[ ! "$2" ]]; then
+  origin_file="$1"
+  tmp_file="$origin_file.old"
+  new_title="$2"
+  if [[ ! "$new_title" ]]; then
    abort_with "2 parameters required"
   fi
 
-  if [[ ! -f "$1" ]]; then
-   abort_with "Not a file: $1"
+  if [[ ! -f "$origin_file" ]]; then
+   abort_with "Not a file: $origin_file"
   fi
 
-  TMP_FILE="$1.old"
-  mv "$1" "$TMP_FILE"
-  ffmpeg -i "$TMP_FILE" -stats -v 0 -c copy -metadata title="$2" "$1"
-  rm "$TMP_FILE"
+  mv "$origin_file" "$tmp_file"
+  ffmpeg -i "$tmp_file" -stats -v 0 -c copy -metadata title="$new_title" "$origin_file"
+  if [[ $? -eq 0 ]]; then
+    rm "$tmp_file"
+  else
+    printf "ffmpeg error, restoring file... "
+    mv "$tmp_file" "$origin_file"
+    printf "done\n"
+    exit 1
+  fi
 }
 
 dry_run_message() {
@@ -47,22 +56,25 @@ if [[ "$1" == "-auto" ]]; then
   fi
 
   echo "setting titles in all *.$2 files..."
+  input_files=()
+  while read line; do
+    input_files+=("$line")
+  done < <(find . -type f -name "*.${2}")
+
   epDiv="S[0-9][0-9]E[0-9][0-9]"
-  for infile in *.${2}; do
-    if [[ -f "$infile" ]]; then
-      title=$(echo "$infile" | sed "s/.*$epDiv.\(.*\)\.$2/\1/")
-      epNum=$(echo "$infile" | sed "s/.*\($epDiv\).*/\1/")
-      title="${epNum} ${title//./ }"
+  for infile in "${input_files[@]}"; do
+    title=$(echo "$infile" | sed "s/.*$epDiv.\(.*\)\.$2/\1/")
+    epNum=$(echo "$infile" | sed "s/.*\($epDiv\).*/\1/")
+    title="${epNum} ${title//./ }"
 
-      if [[ -z $SMALL_FMT ]]; then
-        serName=$(echo "$infile" | sed "s/\(.*\)\.$epDiv.*/\1/")
-        title="${serName//./ } ${title}"
-      fi
+    if [[ -z $SMALL_FMT ]]; then
+      serName=$(echo "${infile/*\/}" | sed "s/\(.*\)\.$epDiv.*/\1/")
+      title="${serName//./ } ${title}"
+    fi
 
-      echo -e "$infile <${COL_GREEN}${title}${COL_DEFAULT}>"
-      if [[ -z $DRYRUN ]]; then
-         replace_title "$infile" "$title"
-      fi
+    echo -e "$infile <${COL_GREEN}${title}${COL_DEFAULT}>"
+    if [[ -z $DRYRUN ]]; then
+       replace_title "$infile" "$title"
     fi
   done
 
